"""add exercise first_attempt_incorrect columns

Revision ID: 39248ae77a0a
Revises: 9792016c36df
Create Date: 2026-09-14 23:00:37.950199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39248ae77a0a'
down_revision: Union[str, None] = '9792016c36df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The model gained these columns in 9ece800 without a revision, so every
    # Exercise query (QuickMode, the practice bank) failed with "no such column"
    # on real databases while tests (create_all) passed.
    # server_default: SQLite cannot add a NOT NULL column to existing rows
    # without one (autogenerate omitted it).
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_attempt_incorrect', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('first_attempt_incorrect_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('first_attempt_incorrect_date')
        batch_op.drop_column('first_attempt_incorrect')

    # ### end Alembic commands ###
