"""Add flashcards.polish_sentence (Polish translation of the example sentence)

(Original autogenerate message was a misnomer: this revision only adds the
flashcards column; renamed to example_translation in bca470c068e6.)

Revision ID: 435f7893aa06
Revises: 39248ae77a0a
Create Date: 2026-09-18 11:12:57.833320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435f7893aa06'
down_revision: Union[str, None] = '39248ae77a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('polish_sentence', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_column('polish_sentence')

    # ### end Alembic commands ###
