"""Empty revision (no-op)

Autogenerated for flashcard audio preferences on the user model, which were
never added (they live per device in the browser). Kept only because existing
databases are already stamped with this revision id.

Revision ID: 6a3fafbb9b13
Revises: 435f7893aa06
Create Date: 2026-09-18 11:13:14.154320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3fafbb9b13'
down_revision: Union[str, None] = '435f7893aa06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
