"""add_flashcard_mnemonic_image_path

Revision ID: 9792016c36df
Revises: 9c1a1e9b7b4f
Create Date: 2026-08-22 15:43:42.715100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9792016c36df'
down_revision: Union[str, None] = '9c1a1e9b7b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mnemonic_image_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_column('mnemonic_image_path')

    # ### end Alembic commands ###
