"""baseline schema

Revision ID: ff1cf77eb17f
Revises: 
Create Date: 2026-07-25 22:06:44.363138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1cf77eb17f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('native_language', sa.String(), nullable=True),
    sa.Column('target_language', sa.String(), nullable=True),
    sa.Column('cefr_level', sa.String(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('streak_freezes', sa.Integer(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('language_profiles', sa.Text(), nullable=True),
    sa.Column('sleep_data', sa.Text(), nullable=True),
    sa.Column('login_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_token')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_type', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_type', name='uq_user_achievement_type')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('conversation_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('native_language', sa.String(), nullable=False),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language', 'day_number', name='uq_user_lang_day')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_user_id'), ['user_id'], unique=False)

    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('plan_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_plans_user_id'), ['user_id'], unique=False)

    op.create_table('sync_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_events_client_event_id'), ['client_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sync_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_events_user_id'), ['user_id'], unique=False)

    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'test_type', 'language', 'created_at', name='uq_user_test_type_lang_date')
    )
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_results_user_id'), ['user_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cefr_level', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('retrievability', sa.Float(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('lapses', sa.Integer(), nullable=True),
    sa.Column('fsrs_state', sa.String(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('last_review_date', sa.DateTime(), nullable=True),
    sa.Column('memory_strength', sa.Float(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_user_id'), ['user_id'], unique=False)

    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('cefr_level', sa.String(), nullable=True),
    sa.Column('exercise_type', sa.String(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('skill_tag', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('source_lesson_id', sa.Integer(), nullable=True),
    sa.Column('variant_of', sa.Integer(), nullable=True),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('retrievability', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('lapses', sa.Integer(), nullable=True),
    sa.Column('fsrs_state', sa.String(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('last_review_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variant_of'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_skill_tag'), ['skill_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_user_id'), ['user_id'], unique=False)

    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('lesson_day', sa.Integer(), nullable=True),
    sa.Column('lesson_topic', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('isImportant', sa.Boolean(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('retrievability', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('lapses', sa.Integer(), nullable=True),
    sa.Column('fsrs_state', sa.String(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('last_review_date', sa.DateTime(), nullable=True),
    sa.Column('correct_recall_sessions', sa.Integer(), nullable=True),
    sa.Column('last_recall_date', sa.DateTime(), nullable=True),
    sa.Column('is_mastered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('interleaving_bonus', sa.Float(), nullable=True),
    sa.Column('interference_penalty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcards_user_id'), ['user_id'], unique=False)

    op.create_table('topic_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_items_topic_id'), ['topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_items_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topic_items_id'))

    op.drop_table('topic_items')
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcards_user_id'))
        batch_op.drop_index(batch_op.f('ix_flashcards_id'))

    op.drop_table('flashcards')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_user_id'))
        batch_op.drop_index(batch_op.f('ix_exercises_topic'))
        batch_op.drop_index(batch_op.f('ix_exercises_skill_tag'))
        batch_op.drop_index(batch_op.f('ix_exercises_language'))
        batch_op.drop_index(batch_op.f('ix_exercises_id'))

    op.drop_table('exercises')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_user_id'))
        batch_op.drop_index(batch_op.f('ix_topics_id'))

    op.drop_table('topics')
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_test_results_id'))

    op.drop_table('test_results')
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_sync_events_id'))
        batch_op.drop_index(batch_op.f('ix_sync_events_client_event_id'))

    op.drop_table('sync_events')
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_plans_id'))

    op.drop_table('study_plans')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_user_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_user_id'))

    op.drop_table('conversation_sessions')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_user_id'))
        batch_op.drop_index(batch_op.f('ix_achievements_id'))

    op.drop_table('achievements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
