import { useState, useEffect, useCallback, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Dumbbell, Check, X, ArrowRight, Sparkles, Loader2, Shuffle, RotateCcw,
  CloudOff, UploadCloud,
} from 'lucide-react'
import {
  getUserId, getPracticeSet, answerExercise, generateExerciseVariants, getExerciseStats,
  getOfflinePack,
} from '../api/client'
import { savePack, loadPack, gradeLocally, enqueueAnswer } from '../utils/offlineQueue'
import { PageLoader } from '../components/LoadingSpinner'
import SpecialChars from '../components/SpecialChars'
import { useLanguage } from '../hooks/useLanguage'
import { useOfflineSync } from '../hooks/useOfflineSync'

const SET_SIZE = 10

export default function Practice() {
  const [set, setSet] = useState(null)
  const [loading, setLoading] = useState(true)
  const [index, setIndex] = useState(0)
  const [typed, setTyped] = useState('')
  const [result, setResult] = useState(null)
  const [checking, setChecking] = useState(false)
  const [score, setScore] = useState({ correct: 0, total: 0 })
  const [generating, setGenerating] = useState(false)
  const [genMsg, setGenMsg] = useState('')
  const [weakSkills, setWeakSkills] = useState([])
  // Notice shown when the server auto-adds exercises after a run of errors
  const [autoNotice, setAutoNotice] = useState('')
  // Offline state
  const [offlineMode, setOfflineMode] = useState(false)
  const navigate = useNavigate()
  const userId = getUserId()
  const { t, targetLanguage } = useLanguage()
  const answerRef = useRef(null)
  const { pending, syncing, lastSynced, refresh: refreshPending } = useOfflineSync()

  /** Build a practice set out of the locally stored pack. */
  const setFromPack = useCallback(() => {
    const pack = loadPack()
    if (!pack?.exercises?.length) return null
    const now = Date.now()
    const due = pack.exercises.filter(
      e => !e.next_review_date || new Date(e.next_review_date).getTime() <= now
    )
    const chosen = (due.length ? due : pack.exercises).slice(0, SET_SIZE)
    return {
      exercises: chosen,
      due_count: due.length,
      interleaved_count: 0,
      generated_new: 0,
      weak_skills: [],
      offline: true,
    }
  }, [])

  const load = useCallback((includeNew = false) => {
    setLoading(true)
    const reset = (data, offline) => {
      setSet(data)
      setOfflineMode(offline)
      setIndex(0)
      setTyped('')
      setResult(null)
      setScore({ correct: 0, total: 0 })
      setWeakSkills(data?.weak_skills || [])
      setAutoNotice('')
    }

    return getPracticeSet(userId, { size: SET_SIZE, includeNew })
      .then(data => {
        reset(data, false)
        // Keep an up-to-date pack around for the next time there is no network
        getOfflinePack(userId).then(savePack).catch(() => {})
      })
      .catch(() => {
        const fallback = setFromPack()
        if (fallback) reset(fallback, true)
        else setSet(null)
      })
      .finally(() => setLoading(false))
  }, [userId, setFromPack])

  useEffect(() => {
    if (!userId) { navigate('/placement'); return }
    load()
  }, [userId])

  const exercises = set?.exercises || []
  const current = exercises[index]
  const finished = exercises.length > 0 && index >= exercises.length

  /** Grade on the device and queue the answer for the next sync. */
  const answerOffline = (exercise, answerText) => {
    const expected = exercise.answer
    if (expected == null) return null // pack lacks the answer — cannot grade here
    const correct = gradeLocally(expected, answerText)
    enqueueAnswer({ exerciseId: exercise.id, userId, answer: answerText, correct })
    refreshPending()
    return {
      correct,
      expected_answer: expected,
      feedback: exercise.feedback,
      skill_tag: exercise.skill_tag,
      interval_days: null,
      queued: true,
    }
  }

  const handleCheck = async () => {
    if (!typed.trim() || !current) return
    setChecking(true)
    try {
      let r
      if (!navigator.onLine) {
        r = answerOffline(current, typed)
      } else {
        try {
          r = await answerExercise(current.id, userId, typed)
        } catch {
          // Network died mid-session — fall back to local grading
          r = answerOffline(current, typed)
        }
      }
      setResult(r)
      if (r) setScore(s => ({ correct: s.correct + (r.correct ? 1 : 0), total: s.total + 1 }))
      // Server auto-generated fresh variants for a skill being failed: fold them
      // into the current session so the struggling skill is reinforced right away.
      if (r?.auto_generated > 0 && Array.isArray(r.auto_generated_exercises)) {
        setSet(s => s ? { ...s, exercises: [...s.exercises, ...r.auto_generated_exercises] } : s)
        // Different message for the two triggers: repeated errors vs memorisation
        const key = r.auto_generated_reason === 'mastery'
          ? 'practice.autoGeneratedMastery'
          : 'practice.autoGenerated'
        setAutoNotice(
          t(key)
            .replace('{n}', r.auto_generated)
            .replace('{skill}', r.auto_generated_skill || '')
        )
      }
    } finally {
      setChecking(false)
    }
  }

  const next = () => {
    setTyped('')
    setResult(null)
    const upcoming = index + 1
    setIndex(upcoming)
    if (upcoming >= exercises.length && navigator.onLine) {
      getExerciseStats(userId)
        .then(s => setWeakSkills(s.weak_skills || []))
        .catch(() => {})
    }
    // Refocus the (now re-enabled) answer field so typing can continue at once.
    requestAnimationFrame(() => answerRef.current?.focus())
  }

  // Two-stage Enter: the first Enter (in the enabled input) submits the answer;
  // once a result is shown the input is disabled, so a document-level listener
  // makes the second Enter advance to the next exercise.
  useEffect(() => {
    if (!result) return
    const onKey = (e) => {
      if (e.key === 'Enter') { e.preventDefault(); next() }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [result])

  const handleGenerate = async () => {
    setGenerating(true)
    setGenMsg('')
    try {
      const r = await generateExerciseVariants(userId, weakSkills.length ? weakSkills : undefined)
      setGenMsg(r.added > 0 ? t('practice.generated').replace('{n}', r.added) : t('practice.nothingGenerated'))
      if (r.added > 0) await load()
    } catch {
      setGenMsg(t('practice.generateFailed'))
    } finally {
      setGenerating(false)
    }
  }

  const handleDownloadPack = async () => {
    try {
      const pack = await getOfflinePack(userId)
      setGenMsg(savePack(pack) ? t('practice.packSaved').replace('{n}', pack.exercises.length) : t('practice.packFailed'))
    } catch {
      setGenMsg(t('practice.packFailed'))
    }
  }

  if (loading) return <PageLoader />

  if (!set || exercises.length === 0) {
    return (
      <div className="max-w-2xl mx-auto p-4">
        <h1 className="text-2xl font-bold flex items-center gap-2 mb-1 text-indigo-300">
          <Dumbbell className="w-6 h-6" /> {t('practice.title')}
        </h1>
        <div className="card mt-4 text-center">
          <p className="text-gray-300">{t('practice.emptyBank')}</p>
          <div className="flex gap-2 justify-center mt-4 flex-wrap">
            <button className="btn-primary" onClick={() => navigate('/lesson')}>
              {t('practice.goToLesson')}
            </button>
          </div>
          {genMsg && <p className="text-sm text-gray-400 mt-3">{genMsg}</p>}
        </div>
      </div>
    )
  }

  return (
    <div className="max-w-2xl mx-auto p-4">
      <h1 className="text-2xl font-bold flex items-center gap-2 mb-1 text-indigo-300">
        <Dumbbell className="w-6 h-6" /> {t('practice.title')}
      </h1>
      <p className="text-gray-400 text-sm mb-4">{t('practice.subtitle')}</p>

      <div className="flex flex-wrap gap-2 mb-4 text-xs items-center">
        <span className="px-2.5 py-1 rounded-lg bg-indigo-900/40 text-indigo-200">
          {t('practice.due')}: {set.due_count}
        </span>
        {set.interleaved_count > 0 && (
          <span className="px-2.5 py-1 rounded-lg bg-purple-900/40 text-purple-200 flex items-center gap-1">
            <Shuffle className="w-3 h-3" /> {t('practice.interleaved')}: {set.interleaved_count}
          </span>
        )}
        {set.generated_new > 0 && (
          <span className="px-2.5 py-1 rounded-lg bg-emerald-900/40 text-emerald-200">
            {t('practice.new')}: {set.generated_new}
          </span>
        )}
        {offlineMode && (
          <span className="px-2.5 py-1 rounded-lg bg-amber-900/40 text-amber-200 flex items-center gap-1">
            <CloudOff className="w-3 h-3" /> {t('practice.offlineMode')}
          </span>
        )}
        {pending > 0 && (
          <span className="px-2.5 py-1 rounded-lg bg-sky-900/40 text-sky-200 flex items-center gap-1">
            {syncing ? <Loader2 className="w-3 h-3 animate-spin" /> : <UploadCloud className="w-3 h-3" />}
            {t('practice.pending').replace('{n}', pending)}
          </span>
        )}
      </div>
      {lastSynced > 0 && pending === 0 && (
        <p className="text-xs text-gray-400 -mt-2 mb-3">
          {t('practice.synced').replace('{n}', lastSynced)}
        </p>
      )}
      {autoNotice && (
        <div className="mb-4 px-3 py-2 rounded-lg bg-emerald-900/30 border border-emerald-700/40 text-emerald-200 text-sm flex items-start gap-2">
          <Sparkles className="w-4 h-4 mt-0.5 shrink-0" /> {autoNotice}
        </div>
      )}

      {finished ? (
        <div className="card text-center">
          <Check className="w-10 h-10 text-emerald-400 mx-auto mb-2" />
          <p className="text-emerald-300 font-semibold">
            {t('practice.done')} {score.correct}/{score.total}
          </p>
          {pending > 0 && (
            <p className="text-xs text-sky-300 mt-2">{t('practice.willSync').replace('{n}', pending)}</p>
          )}
          {weakSkills.length > 0 && (
            <div className="mt-4">
              <p className="text-sm text-gray-400 mb-2">
                {t('practice.weakSkills')}: {weakSkills.join(', ')}
              </p>
              <button
                className="btn-secondary flex items-center gap-2 mx-auto"
                onClick={handleGenerate}
                disabled={generating || offlineMode}
              >
                {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                {t('practice.generateForWeak')}
              </button>
            </div>
          )}
          {genMsg && <p className="text-sm text-gray-400 mt-3">{genMsg}</p>}
          <div className="flex gap-2 justify-center mt-4 flex-wrap">
            <button className="btn-primary flex items-center gap-2" onClick={() => load()}>
              <RotateCcw className="w-4 h-4" /> {t('practice.again')}
            </button>
            <button className="btn-secondary" onClick={handleDownloadPack} disabled={offlineMode}>
              {t('practice.downloadPack')}
            </button>
          </div>
        </div>
      ) : (
        <div className="card">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs text-gray-500">{index + 1} / {exercises.length}</span>
            {current.skill_tag && (
              <span className="text-xs px-2 py-0.5 rounded bg-gray-800 text-gray-400">
                {current.skill_tag}
              </span>
            )}
          </div>

          {current.instruction && (
            <p className="text-gray-400 text-sm mb-2">{current.instruction}</p>
          )}
          <p className="text-gray-100 text-lg mb-4">{current.prompt}</p>

          <input
            ref={answerRef}
            type="text"
            value={typed}
            onChange={e => setTyped(e.target.value)}
            onKeyDown={e => { if (e.key === 'Enter' && !result) handleCheck() }}
            disabled={!!result}
            placeholder={t('practice.placeholder')}
            className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 text-gray-100 focus:outline-none focus:border-indigo-600 disabled:opacity-70"
          />
          {!result && (
            <SpecialChars language={targetLanguage} inputRef={answerRef} value={typed} onChange={setTyped} />
          )}

          {!result ? (
            <button
              onClick={handleCheck}
              disabled={!typed.trim() || checking}
              className="btn-primary w-full mt-3 flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {checking ? <Loader2 className="w-4 h-4 animate-spin" /> : <Check className="w-4 h-4" />}
              {t('practice.check')}
            </button>
          ) : (
            <div className="mt-4">
              <div className={`flex items-center gap-2 mb-2 font-semibold ${result.correct ? 'text-emerald-400' : 'text-red-400'}`}>
                {result.correct ? <Check className="w-5 h-5" /> : <X className="w-5 h-5" />}
                {result.correct ? t('practice.correct') : t('practice.wrong')}
              </div>
              {!result.correct && (
                <p className="text-sm text-gray-300 bg-gray-800/60 rounded-lg p-3 mb-2">
                  <span className="text-gray-500">{t('practice.expected')}: </span>
                  <span className="text-emerald-300">{result.expected_answer}</span>
                </p>
              )}
              {result.feedback && (
                <p className="text-sm text-gray-400 mb-3">{result.feedback}</p>
              )}
              <p className="text-xs text-gray-500 mb-3">
                {result.queued
                  ? t('practice.queued')
                  : `${t('practice.nextReview')}: ${result.interval_days} ${t('practice.days')}`}
              </p>
              <button onClick={next} className="btn-primary w-full flex items-center justify-center gap-2">
                {t('practice.next')} <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
